My_Social_Project/My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from post_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('post/', include('post_app.urls')),
    path('', views.home_view, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Social_Project/login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
]

My_Social_Project/post_app/urls.py
from . import views
from django.urls import path
app_name = 'post_app'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/',views.unliked, name='unliked'),
]

My_Social_Project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_picture = models.ImageField(upload_to='dps', blank=True)
    full_name = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    full_name = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

My_Social_Project/login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'user@example.com'}))
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password1 = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter the password'})
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'password'})
    )
    class Meta:
        model = User
        fields = ('username', 'password')

class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user', ) 

My_Social_Project/login_app/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import CreateNewUser, LoginForm, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from .models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from post_app.forms import PostForm
from django.contrib.auth.models import User

# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('login_app:login'))
    
    return render(request, 'login_app/sign_up.html', {'title': 'Sign Up . Instagram', 'form': form})

def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('post_app:home'))

    return render(request, 'login_app/login.html', {'form': form})

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/profile.html', {'form': form})

@login_required 
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))

@login_required 
def profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('post_app:home'))
    return render(request, 'login_app/user.html', {'form': form})

@login_required 
def user(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/user_other.html', {'user_other': user_other, 'already_followed': already_followed})

@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()

    return HttpResponseRedirect(reverse('login_app:user', kwargs={'username': username}))

@login_required 
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('login_app:user', kwargs={'username': username}))

My_Social_Project/templates/login_app/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block css_block %}
<style>
  .sign_up {
    width: 450px;
    border: 1px solid #ccc;
    padding: 40px;
  }
  .log_in {
    width: 450px;
    padding: 20px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}
{% block body_block %}
<center>
<div class='sign_up'>
  <h5>Log in to your account.</h5>
  <form method="POST">
    {{ form|crispy}}
    {% csrf_token %}
    <button type="submit" style="width:100%" class="btn btn-primary">Login</button>
  </form>
</div>
<div class="log_in my-3">
    <p>Don't have an account? <a href="{% url 'login_app:sign_up' %}">Sign up</a></p>
  </div>
</center>
{% endblock %}

My_Social_Project/templates/login_app/navbar.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>{% block title_block %} Social {% endblock %}</title>
    {% block css_block %}

    {% endblock %}
  </head>
  <body>
    <!-- navbar section -->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'post_app:home' %}">ConnectED.com</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_app:logout' %}">Log out</a>
          </li>
          <li class="nav-item">
            {% if user.user_profile.profile_picture %}
            <a class="nav-link" href="{% url 'login_app:profile' %}"><img src="/media/{{user.user_profile.profile_picture}}" alt="" width="23px" height="23px" class="rounded-circle">{{user.username}}</a>
            {% else %}
            <a class="nav-link" href="{% url 'login_app:profile' %}"><img src="/static/images/unisex_avatar.jpg" width="23px" height="23px" class="rounded-circle" alt="default">{{user.username}}</a>
            {% endif %}
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container" style='padding-top:20px'>
    {% block body_block %} {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

My_Social_Project/templates/login_app/profile.html
{% extends 'login_app/navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit profile {% endblock %}
{% block css_block %}

{% endblock %}
{% block body_block %}

<div class='edit-profile'>
    <h5>Edit your profile</h5>
    <form method="POST" enctype="multipart/form-data">
      {{ form|crispy}}
      {% csrf_token %}
      <button type="submit" style="width:100%" class="btn btn-primary">Update</button>
    </form>
  </div>

{% endblock %}

My_Social_Project/templates/login_app/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
<style>
  .sign_up {
    width: 450px;
    border: 1px solid #ccc;
    padding: 40px;
  }
  .log_in {
    width: 450px;
    padding: 20px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}
{% block body_block %}
<center>
<div class='sign_up'>
  <h5>Sign up to see photos from your friends.</h5>
  <form method="POST">
    {{ form|crispy}}
    {% csrf_token %}
    <button type="submit" style="width:100%" class="btn btn-primary">Sign up</button>
  </form>
</div>
<div class="log_in my-3">
  <p>Have an account? <a href="{% url 'login_app:login' %}">Log in</a></p>
</div>
</center>
{% endblock %}

My_Social_Project/templates/login_app/user.html
{% extends 'login_app/navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{user.user_profile.full_name}} {% endblock %}
{% block css_block %}
<style>
    .crop {
        width: 200px;
        height: 200px;
        overflow: hidden;
    }

    .crop img {
        width: 400px;
        height: 300px;
        margin: -75px 0 0 -100px;
    }
</style>
{% endblock %}
{% block body_block %}

<div class="row pt-5">
    <div class="col-sm-4">
        {% if user.user_profile.profile_picture %}
        <img src="/media/{{user.user_profile.profile_picture}}" alt="" width="250px" height="250px"
            class="rounded-circle">
        {% else %}
        <img src="/static/images/unisex_avatar.jpg" width="250px" height="250px" class="rounded-circle" alt="default">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{user.username}} &nbsp; <a href="{% url 'login_app:edit_profile'%}" class="btn btn-primary btn-sm">Edit
                Profile</a></h3><br>
        <h4>{{user.post.count}} posts &nbsp; &nbsp; {{user.following.count}} followers &nbsp; &nbsp;
            {{user.following.count}} following</h4><br>
        <h4>{{user.user_profile.full_name}}</h4>
        <p>{{user.user_profile.description|linebreaks}}</p>
    </div>
</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Post
</button>

<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Post a Photo</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {{form|crispy}}
                    {% csrf_token %}
                    <button type="submit">Post</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<br>
<br>
<div class="row m-5">
    {% for post in user.post.all %}
    <div class="col-sm-4">
        <div class="crop">
            <img src="/media/{{post.image}}" title="{{post.caption}}">
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

My_Social_Project/templates/login_app/user_other.html
{% extends 'login_app/navbar.html' %}
{%block title_block %} {{user_other.user_profile.full_name}} (@{{user_other.username}}) {%endblock%}
{%block css_block%}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}
{% block body_block %}
<div class="row">
  <div class="col-sm-4">
    {% if user_other.user_profile.profile_picture %}
    <img src="/media/{{user_other.user_profile.profile_picture}}" width="250px" height="250px" class="rounded-circle">
    {% else %}
    <img src="/static/images/unisex_avatar.jpg" width="250px" height="250px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h1>{{user_other.username}} &nbsp;
      {% if not already_followed %}
      <a href="{% url 'login_app:follow' username=user_other.username%}" class="btn btn-primary">Follow</a>
      {% else %}
      <a href="{% url 'login_app:follow' username=user_other.username%}" class="btn btn-primary">Unfollow</a>
      {% endif %}
    </h1>
    <br>
    <h4>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} followers &nbsp; &nbsp; {{user_other.follower.count}} following</h4>
    <br>
    <h3>{{user_other.user_profile.full_name}}</h3>
    <p>{{user_other.user_profile.description|linebreaks}}</p>
  </div>
</div>
<hr>
<br>
<br>
<div class="row">
  {% for post in user_other.post.all %}
  <div class="crop">
    <img src="/media/{{post.image}}" title="{{post.caption}}">
  </div>

  {% endfor %}
</div>
{% endblock %}